version: 2
jobs:
  build-and-deploy:
    docker:
      - image: 742965927775.dkr.ecr.us-east-1.amazonaws.com/itskoko/koko-ci-tools:latest
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build
          command: koko-build itskoko/k8s-ci-purger

      - run:
          name: Deploy
          command: koko-deploy itskoko/k8s-ci-purger deployment/k8s-ci-purger

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-deploy:
          context: org-global
          filters:
            branches:
              only: /^(master|circleci)$/

